---

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Install hostname template
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  notify: "Temporary hostname setup"

- name: Update hosts file
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1 {{ inventory_hostname }} {{ inventory_hostname }}.global.corp.domain localhost"
  notify: "Temporary hostname setup"

- name: Ensure any pending handlers are run now
  meta: flush_handlers

