
# Simplified version of the full testing process that takes a list of test cases ("dns_entries"),
#   performs the lookup, and compares the results to the provided address.
#
# Sample test data:
#   test_domains:
#     - { domain: "central-dns01.global.corp", address: "10.0.10.50" }
#     - { domain: "{{ central_dns_hostname }}", address: "{{ central_dns_ip }}" }
#

- name: Perform nslookup for list of test domains
  command: "nslookup {{ item.domain }} localhost"
  with_items: "{{ dns_entries }}"
  register: test_result
  failed_when: item.address != test_result.stdout_lines[-1][9:]
  changed_when: False