---

- name: Get subnet ID
  local_action: ec2_vpc_subnet_facts
  args:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ aws_subnet_name }}"
  register: subnet_facts

- set_fact:
    subnet_id: "{{ subnet_facts.subnets[0].id }}"

- name: Terminate any running instances
  local_action: ec2
  args:
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_ami }}"
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ subnet_id }}"
    exact_count: 0
    count_tag:
      Name: "{{ aws_name_tag }}"
    wait: yes
  register: ec2